/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedbackIndexRouteImport } from './routes/feedback/index'
import { Route as AlertsIndexRouteImport } from './routes/alerts/index'
import { Route as AlertsSkuIdRouteImport } from './routes/alerts/$skuId'
import { Route as SettingsRulesIndexRouteImport } from './routes/settings/rules/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackIndexRoute = FeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsSkuIdRoute = AlertsSkuIdRouteImport.update({
  id: '/alerts/$skuId',
  path: '/alerts/$skuId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRulesIndexRoute = SettingsRulesIndexRouteImport.update({
  id: '/settings/rules/',
  path: '/settings/rules/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts/$skuId': typeof AlertsSkuIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/feedback/': typeof FeedbackIndexRoute
  '/settings/rules/': typeof SettingsRulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts/$skuId': typeof AlertsSkuIdRoute
  '/alerts': typeof AlertsIndexRoute
  '/feedback': typeof FeedbackIndexRoute
  '/settings/rules': typeof SettingsRulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts/$skuId': typeof AlertsSkuIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/feedback/': typeof FeedbackIndexRoute
  '/settings/rules/': typeof SettingsRulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts/$skuId'
    | '/alerts/'
    | '/feedback/'
    | '/settings/rules/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alerts/$skuId' | '/alerts' | '/feedback' | '/settings/rules'
  id:
    | '__root__'
    | '/'
    | '/alerts/$skuId'
    | '/alerts/'
    | '/feedback/'
    | '/settings/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsSkuIdRoute: typeof AlertsSkuIdRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  FeedbackIndexRoute: typeof FeedbackIndexRoute
  SettingsRulesIndexRoute: typeof SettingsRulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/': {
      id: '/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof FeedbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$skuId': {
      id: '/alerts/$skuId'
      path: '/alerts/$skuId'
      fullPath: '/alerts/$skuId'
      preLoaderRoute: typeof AlertsSkuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/rules/': {
      id: '/settings/rules/'
      path: '/settings/rules'
      fullPath: '/settings/rules/'
      preLoaderRoute: typeof SettingsRulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsSkuIdRoute: AlertsSkuIdRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  FeedbackIndexRoute: FeedbackIndexRoute,
  SettingsRulesIndexRoute: SettingsRulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
