/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedbackIndexRouteImport } from './routes/feedback/index'
import { Route as AlertsIndexRouteImport } from './routes/alerts/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as AlertsSkuIdRouteImport } from './routes/alerts/$skuId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackIndexRoute = FeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsSkuIdRoute = AlertsSkuIdRouteImport.update({
  id: '/alerts/$skuId',
  path: '/alerts/$skuId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts/$skuId': typeof AlertsSkuIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/alerts/': typeof AlertsIndexRoute
  '/feedback/': typeof FeedbackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts/$skuId': typeof AlertsSkuIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/alerts': typeof AlertsIndexRoute
  '/feedback': typeof FeedbackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts/$skuId': typeof AlertsSkuIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/alerts/': typeof AlertsIndexRoute
  '/feedback/': typeof FeedbackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alerts/$skuId'
    | '/demo/tanstack-query'
    | '/alerts/'
    | '/feedback/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alerts/$skuId'
    | '/demo/tanstack-query'
    | '/alerts'
    | '/feedback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/alerts/$skuId'
    | '/demo/tanstack-query'
    | '/alerts/'
    | '/feedback/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlertsSkuIdRoute: typeof AlertsSkuIdRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  FeedbackIndexRoute: typeof FeedbackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/': {
      id: '/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof FeedbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$skuId': {
      id: '/alerts/$skuId'
      path: '/alerts/$skuId'
      fullPath: '/alerts/$skuId'
      preLoaderRoute: typeof AlertsSkuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlertsSkuIdRoute: AlertsSkuIdRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  FeedbackIndexRoute: FeedbackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
