/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppFeedbackIndexRouteImport } from './routes/_app/feedback/index'
import { Route as AppChatIndexRouteImport } from './routes/_app/chat/index'
import { Route as AppAlertsIndexRouteImport } from './routes/_app/alerts/index'
import { Route as AppSettingsRulesIndexRouteImport } from './routes/_app/settings/rules/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackIndexRoute = AppFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsIndexRoute = AppAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRulesIndexRoute = AppSettingsRulesIndexRouteImport.update({
  id: '/settings/rules/',
  path: '/settings/rules/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/alerts/': typeof AppAlertsIndexRoute
  '/chat/': typeof AppChatIndexRoute
  '/feedback/': typeof AppFeedbackIndexRoute
  '/settings/rules/': typeof AppSettingsRulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/alerts': typeof AppAlertsIndexRoute
  '/chat': typeof AppChatIndexRoute
  '/feedback': typeof AppFeedbackIndexRoute
  '/settings/rules': typeof AppSettingsRulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_app/alerts/': typeof AppAlertsIndexRoute
  '/_app/chat/': typeof AppChatIndexRoute
  '/_app/feedback/': typeof AppFeedbackIndexRoute
  '/_app/settings/rules/': typeof AppSettingsRulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/alerts/'
    | '/chat/'
    | '/feedback/'
    | '/settings/rules/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/alerts' | '/chat' | '/feedback' | '/settings/rules'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/login/'
    | '/_app/alerts/'
    | '/_app/chat/'
    | '/_app/feedback/'
    | '/_app/settings/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback/': {
      id: '/_app/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof AppFeedbackIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts/': {
      id: '/_app/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AppAlertsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/rules/': {
      id: '/_app/settings/rules/'
      path: '/settings/rules'
      fullPath: '/settings/rules/'
      preLoaderRoute: typeof AppSettingsRulesIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAlertsIndexRoute: typeof AppAlertsIndexRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppFeedbackIndexRoute: typeof AppFeedbackIndexRoute
  AppSettingsRulesIndexRoute: typeof AppSettingsRulesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAlertsIndexRoute: AppAlertsIndexRoute,
  AppChatIndexRoute: AppChatIndexRoute,
  AppFeedbackIndexRoute: AppFeedbackIndexRoute,
  AppSettingsRulesIndexRoute: AppSettingsRulesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
